language:
  - python
python:
  # https://github.com/travis-ci/travis-ci/issues/2219#issuecomment-41804942
  # https://snarky.ca/how-to-use-your-project-travis-to-help-test-python-itself/
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
before_install:
  # install dependencies for NumPy
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran libatlas-base-dev
  - sudo apt-get install -qq python-numpy
  - sudo apt-get install -qq pandoc
install:
  - python setup.py install
  - pip install -U pip wheel
  - pip install -U --use-wheel pytest pytest-cov
  - pip install -U tinysegmenter
  - pip install -U jieba
  - python -c "import nltk; nltk.download('punkt')"
script:
  - py.test tests
